OpenMS/pyopenms-docs

src/specViewer/SpecViewer.py

Allow browsing spectra using the keyboard

[FEATURE] browse spectra by keyboard

---

src/specViewer/SpecViewer.py

[STYLE] changed peak color to black

---

src/specViewer/SpecViewer.py

Reverts OpenMS/pyopenms-extra#14

Revert "Feature/improved peak highlight"

---

docs/source/datastructures_id.rst

[DOC] extend peptide/protein id docu

---

.github/workflows/Build_Jupyter_Notebooks.yml
requirements.txt

This PR will fix the **Build_Jupyter_Notebooks.yml** workflow.

fixing dependencies

---

docs/source/parameter_handling.rst

Add an example of how to initialize a StringList (Param)

Add example for a StringList

---

docs/source/aasequences.rst

[ADD] Example for parsing modification AASequence

---

docs/source/chemistry.rst
docs/source/data_manipulation.rst
docs/source/datastructures.rst
docs/source/index.rst
docs/source/mass_decomposition.rst
docs/source/memory_management.rst
docs/source/mzMLFileFormat.rst
docs/source/normalization.rst
docs/source/other_file_handling.rst

fixes #79 
fixes #80 
edit:
fixes #112

[FIX] Subsection positioning

---

docs/source/getting_started.rst

[FIX] TIC in getting started

---

docs/source/id_by_mz.rst

Plotting consensus maps before and after alignment with matplotlib according to the map alignment tutorial.

update map alignment visualization in example workflow

---

docs/source/datastructures_id.rst

Adding Note for getIdentifier Method

---

docs/source/index.rst
docs/source/pandas_df_conversion.rst
src/data/BSA1_F1_idmapped.featureXML
src/data/ProteomicsLFQ_1_out.consensusXML

Added a section how to use the pandas data frame conversion functionality.

[FEATURE] pandas DF conversion tutorial

---

docs/source/parameter_handling.rst

add some simple functions, dealing with Param

add some functions

---

docs/source/index.rst
docs/source/massql.rst
requirements.txt

Example to export an MSExperiment for queries with MassQL.

tutorial for massql export

---

docs/source/chemistry.rst

add an example on how to incorporate specific isotopes into a molecular formula

[DOC] add isotopes to molecular formula

---

README.md
docs/source/ML_tutorial.rst
docs/source/algorithms.rst
docs/source/centroiding.rst
docs/source/chromatographic_analysis.rst
docs/source/contribute.rst
docs/source/datastructures_peak.rst
docs/source/deisotoping.rst
docs/source/digestion.rst
docs/source/feature_detection.rst
docs/source/feature_linking.rst
docs/source/file_handling.rst
docs/source/first_steps.rst
docs/source/hyperscore.rst
docs/source/interactive_plots.rst
docs/source/map_alignment.rst
docs/source/massql.rst
docs/source/mzMLFileFormat.rst
docs/source/mzqc_export.rst
docs/source/normalization.rst
docs/source/other_file_handling.rst
docs/source/pandas_df_conversion.rst
docs/source/peptide_search.rst
docs/source/smoothing.rst
docs/source/spectrumalignment.rst

Fixes https://github.com/OpenMS/pyopenms-docs/issues/269.

Rename occurrences of pyopenms-extra to pyopenms-docs

---

docs/requirements.txt

Update everything but sphinx to newest version.

---

.github/workflows/build-push-notebooks.yaml

Probably ubuntu_latest is now 22.04 and comes with py 3.10

Update py version of wheel to install.

---

.gitignore
docs/source/_ext/glossary_warnings.py
docs/source/conf.py
docs/source/first_steps.rst
docs/source/glossary.rst
docs/source/wrap_classes.rst

[FEATURE] Glossary warnings

---

docs/source/build_from_source.rst

Seems that pytest is needed for testing?

add pytest as a requirement

---

.github/workflows/build-push-notebooks.yaml
.github/workflows/test-notebooks.yml
.github/workflows/test-pr.yaml
README.md
docs/source/installation.rst
docs/source/pandas_df_conversion.rst
postBuild

Pypi local

---

.github/workflows/test-pr.yaml

Path spec should be part of `files:` not `path:`

Fix changed-files

---

.github/workflows/build-push-notebooks.yaml
.github/workflows/test-notebooks.yml
.github/workflows/test-pr.yaml
requirements.txt

Fixes mistake from https://github.com/OpenMS/pyopenms-docs/pull/340

re-added requirements processing

---

docs/source/theoreticalspectrumgenerator.rst

by introducing more parameters.
Fixing the issue https://github.com/OpenMS/pyopenms-docs/issues/291
Corresponding visualization (example image) should be changed in different PR after fixing the issue https://github.com/OpenMS/OpenMS/issues/6701

Expanding theoretical spectrum generation tutorial

---

docs/source/user_guide/peptides_proteins.rst

Reverts OpenMS/pyopenms-docs#391

Revert "Update peptides_proteins.rst"

---

docs/source/user_guide/installation.rst

simple edit to correct pyopenms nightly intto pyopenms

Update installation.rst for pyopenms

---

docs/source/user_guide/installation.rst

Updated in accordance with versions listed in [`python_versions.json`](https://github.com/OpenMS/OpenMS/blob/3965aec2291c113c468c51dfeed75848f89c68ef/.github/workflows/python_versions.json#L2) in the main repo.

Update supported versions of python
